---

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  tasks:
    - name: Include role 'ansible-role-github_cli'
      include_role:
        name: ansible-role-github_cli
